# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project-Alpha2.0' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project-Alpha2.0
    pod 'SnapKit', '~> 4.0.0'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'Alamofire', '~> 4.8.0'
    pod 'AlamofireImage', '~> 3.4.0'
    pod ‘KeychainAccess’

end
